GENERAL:
  model_name: vae
  seed: 11

DATA:
  data_dir: datasets/train
  batch_size: 16
  train_workers: 4

  augmentation: True

LIT_MODEL:
  pretrained_weights:

  # optimizer
  weight_decay: 0.0001
  lr: 0.0005
  # loss
  lambda_kld: 1
  lambda_recon: 0.1
#  lambda_image: 10
#  lambda_latent: 0.5

TRAINER:
  max_epochs: 10000
  progress_bar_refresh_rate: 1
